export const alphabet = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const mockItineraryData = [
  {
    user: "Tuya",
    image: "https://avatar.iran.liara.run/public/girl?username=Tuya",
    name: "Corsica road trip",
    time: 123,
    start: "Ajaccio",
    stops: [
      { location: "Bonifacio", stopover: true },
      { location: "Porto Vecchio", stopover: true },
      { location: "Soveria, Corsica", stopover: true },
      { location: "Bastia", stopover: true },
    ],
    finish: "Calvi",
  },
  {
    user: "Guido",
    image: "https://avatar.iran.liara.run/public/boy?username=Guido",
    name: "London Tour",
    time: 123,
    start: "British Museum",
    stops: [
      { location: "National Gallery", stopover: true },
      { location: "Leicester Square", stopover: true },
      { location: "Piccadilly Circus", stopover: true },
    ],
    finish: "Harrods",
  },
  {
    user: "Cinzia",
    image: "https://avatar.iran.liara.run/public/girl?username=Cinzia",
    name: "Mauritius Summer",
    time: 123,
    start: "Port Louis, Mauritius",
    stops: [{ location: "Albion, Mauritius", stopover: true }],
    finish: "Souillac, Mauritius",
  },
  {
    user: "Samuele",
    image: "https://avatar.iran.liara.run/public/boy?username=Guido",
    name: "Sicily Experience",
    time: 123,
    start: "Palermo",
    stops: [
      { location: "Messina", stopover: true },
      { location: "Catania", stopover: true },
      { location: "Siracusa", stopover: true },
    ],
    finish: "Noto",
  },
  {
    user: "Silvia",
    image: "https://avatar.iran.liara.run/public/girl?username=Silvia",
    name: "Safari Week",
    time: 123,
    start: "Cape Town",
    stops: [
      { location: "Johannesburg", stopover: true },
      { location: "Kruger Park", stopover: true },
    ],
    finish: "Phalaborwa",
  },
  {
    user: "Alessandro",
    image: "https://avatar.iran.liara.run/public/boy?username=Alessandro",
    name: "Japan Tour",
    time: 123,
    start: "Tokyo",
    stops: [
      { location: "Kyoto", stopover: true },
      { location: "Osaka", stopover: true },
      { location: "Nara", stopover: true },
    ],
    finish: "Hiroshima",
  },
];
